USE MASTER
GO

if exists(select * from sys.databases where name = 'Reddit')
	drop database Reddit
go

CREATE DATABASE Reddit
GO

USE Reddit
GO

CREATE TABLE ImageData
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Photo VARBINARY(MAX) NOT NULL,
)


CREATE TABLE [User]
(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    Email VARCHAR(200) NOT NULL UNIQUE,
    Username VARCHAR(50) NOT NULL UNIQUE,
    ProfilePicture INT REFERENCES ImageData(ID) NULL,
    BirthDate DATETIME NOT NULL,
    [Password] VARBINARY(150) NOT NULL,
    Salt VARCHAR(30) NOT NULL,
)
GO

CREATE TABLE [Group]
(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    OwnerID INT REFERENCES [User](ID) NOT NULL,
    [Name] VARCHAR(50) NOT NULL,
    [Description] VARCHAR(150) NULL,
    [Image] INT REFERENCES ImageData(ID) NULL,
)
GO

CREATE TABLE [UserGroup]
(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    UserID INT NOT NULL REFERENCES [User](ID),
    GroupID INT NOT NULL REFERENCES [Group](ID)
)
GO

CREATE TABLE [Post]
(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    AuthorID INT REFERENCES [User](ID) NOT NULL,
    GroupID INT REFERENCES [Group](ID) NOT NULL,
    Title VARCHAR(50) NOT NULL,
    Content VARCHAR(400) NOT NULL,
    IndexedImage VARBINARY(MAX) NULL,
)
GO

CREATE TABLE [Upvote]
(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    UserID INT REFERENCES [User](ID) NOT NULL,
    PostID INT REFERENCES [Post](ID) NOT NULL,
    [Value] BIT DEFAULT(1) NOT NULL
)
GO

CREATE TABLE [Role]
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL,
)
GO

CREATE TABLE [Permission]
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL,
	[Description] VARCHAR(150) NULL,
)
GO

CREATE TABLE [RolePermission]
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,	
	RoleID INT REFERENCES [Role](ID) NOT NULL,
	PermissionID INT REFERENCES [Permission](ID) NOT NULL
)
GO

